const now = new Date();
const demoPasswordHash = "ZGVtbzEyMzQ=";

const isoDaysFromNow = (days) => {
  const date = new Date(now);
  date.setDate(date.getDate() + days);
  return date.toISOString();
};

const isoDaysAgo = (days) => {
  const date = new Date(now);
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

const lessonContent = (items) => JSON.stringify(items);

export const initialAppData = {
  currentUser: {
    id: "user-1",
    email: "alex@languageboost.app",
    full_name: "Alex Carter",
    passwordHash: demoPasswordHash,
    role: "admin",
    bio: "Learning one useful phrase at a time.",
    native_language: "English",
    target_languages: "Spanish, French, Japanese",
    streak_count: 7,
    longest_streak: 18,
    total_xp: 1240,
    current_level: 5,
    daily_goal_minutes: 20,
    created_date: isoDaysAgo(120),
    updated_date: isoDaysAgo(1),
  },
  users: [
    {
      id: "user-1",
      email: "alex@languageboost.app",
      full_name: "Alex Carter",
      passwordHash: demoPasswordHash,
      role: "admin",
      streak_count: 7,
      total_xp: 1240,
      current_level: 5,
      created_date: isoDaysAgo(120),
    },
    {
      id: "user-2",
      email: "maria@example.com",
      full_name: "Maria Silva",
      passwordHash: demoPasswordHash,
      role: "user",
      streak_count: 24,
      total_xp: 1980,
      current_level: 7,
      created_date: isoDaysAgo(160),
    },
    {
      id: "user-3",
      email: "james@example.com",
      full_name: "James Lee",
      passwordHash: demoPasswordHash,
      role: "user",
      streak_count: 14,
      total_xp: 1750,
      current_level: 6,
      created_date: isoDaysAgo(150),
    },
    {
      id: "user-4",
      email: "yuki@example.com",
      full_name: "Yuki Tanaka",
      passwordHash: demoPasswordHash,
      role: "user",
      streak_count: 10,
      total_xp: 1410,
      current_level: 5,
      created_date: isoDaysAgo(140),
    },
    {
      id: "user-5",
      email: "sofia@example.com",
      full_name: "Sofia Weber",
      passwordHash: demoPasswordHash,
      role: "user",
      streak_count: 5,
      total_xp: 980,
      current_level: 4,
      created_date: isoDaysAgo(90),
    },
  ],
  lessons: [
    {
      id: "lesson-spanish-greetings",
      title: "Spanish Greetings That Sound Natural",
      slug: "spanish-greetings",
      description: "Learn the core phrases used in everyday Spanish introductions.",
      language: "Spanish",
      difficulty_level: "A1",
      lesson_type: "vocabulary",
      duration_minutes: 12,
      xp_reward: 40,
      content: lessonContent([
        { word: "hola", phonetic: "OH-la", definition: "hello", example: "Hola, como estas?" },
        { word: "buenos dias", phonetic: "BWEH-nos DEE-as", definition: "good morning", example: "Buenos dias, senora." },
        { word: "mucho gusto", phonetic: "MOO-cho GOOS-to", definition: "nice to meet you", example: "Mucho gusto, me llamo Ana." },
        { word: "hasta luego", phonetic: "AS-ta loo-EH-go", definition: "see you later", example: "Hasta luego, nos vemos manana." },
      ]),
      is_published: true,
      view_count: 182,
      created_date: isoDaysAgo(30),
      updated_date: isoDaysAgo(4),
    },
    {
      id: "lesson-french-cafe",
      title: "Ordering Smoothly in a French Cafe",
      slug: "french-cafe",
      description: "Useful phrases for ordering drinks and pastries with confidence.",
      language: "French",
      difficulty_level: "A2",
      lesson_type: "speaking",
      duration_minutes: 15,
      xp_reward: 55,
      content: lessonContent([
        { word: "un cafe", phonetic: "uhn ka-FAY", definition: "a coffee", example: "Je voudrais un cafe, s'il vous plait." },
        { word: "l'addition", phonetic: "la-dee-SYON", definition: "the bill", example: "Pouvez-vous apporter l'addition?" },
        { word: "a emporter", phonetic: "ah ahm-por-TAY", definition: "to go", example: "Je prends ca a emporter." },
        { word: "une table", phonetic: "oon TAH-bl", definition: "a table", example: "Nous avons une table pres de la fenetre." },
      ]),
      is_published: true,
      view_count: 154,
      created_date: isoDaysAgo(25),
      updated_date: isoDaysAgo(3),
    },
    {
      id: "lesson-japanese-intro",
      title: "Self Introductions in Japanese",
      slug: "japanese-intro",
      description: "Build a simple self introduction for first meetings.",
      language: "Japanese",
      difficulty_level: "A1",
      lesson_type: "speaking",
      duration_minutes: 14,
      xp_reward: 50,
      content: lessonContent([
        { word: "hajimemashite", phonetic: "ha-jee-meh-MA-shtay", definition: "nice to meet you", example: "Hajimemashite. Alex desu." },
        { word: "watashi wa", phonetic: "wa-TA-shi wa", definition: "I am", example: "Watashi wa Alex desu." },
        { word: "yoroshiku", phonetic: "yo-RO-shee-koo", definition: "please treat me well", example: "Yoroshiku onegaishimasu." },
        { word: "nihon", phonetic: "nee-HON", definition: "Japan", example: "Nihon no ongaku ga suki desu." },
      ]),
      is_published: true,
      view_count: 201,
      created_date: isoDaysAgo(20),
      updated_date: isoDaysAgo(2),
    },
    {
      id: "lesson-german-directions",
      title: "Understanding German Directions",
      slug: "german-directions",
      description: "Ask for and follow directions in common city situations.",
      language: "German",
      difficulty_level: "B1",
      lesson_type: "listening",
      duration_minutes: 18,
      xp_reward: 70,
      content: lessonContent([
        { word: "geradeaus", phonetic: "geh-RAH-day-aus", definition: "straight ahead", example: "Gehen Sie geradeaus." },
        { word: "links", phonetic: "links", definition: "left", example: "Dann links an der Ecke." },
        { word: "die Haltestelle", phonetic: "dee HAL-teh-shtel-leh", definition: "the stop", example: "Die Haltestelle ist dort druben." },
        { word: "um die Ecke", phonetic: "oom dee EK-eh", definition: "around the corner", example: "Das Museum ist um die Ecke." },
      ]),
      is_published: true,
      view_count: 98,
      created_date: isoDaysAgo(12),
      updated_date: isoDaysAgo(1),
    },
    {
      id: "lesson-italian-routine",
      title: "Talking About Your Daily Routine in Italian",
      slug: "italian-routine",
      description: "Describe your day using common verbs and time phrases.",
      language: "Italian",
      difficulty_level: "A2",
      lesson_type: "grammar",
      duration_minutes: 16,
      xp_reward: 60,
      content: lessonContent([
        { word: "mi sveglio", phonetic: "mee SVEH-lyo", definition: "I wake up", example: "Mi sveglio alle sette." },
        { word: "faccio colazione", phonetic: "FAH-cho col-a-tsyo-NEH", definition: "I have breakfast", example: "Faccio colazione a casa." },
        { word: "vado al lavoro", phonetic: "VAH-do al la-VO-ro", definition: "I go to work", example: "Vado al lavoro in treno." },
        { word: "la sera", phonetic: "la SEH-ra", definition: "in the evening", example: "La sera studio italiano." },
      ]),
      is_published: true,
      view_count: 76,
      created_date: isoDaysAgo(8),
      updated_date: isoDaysAgo(1),
    },
  ],
  userProgress: [
    {
      id: "progress-1",
      user_id: "user-1",
      lesson_id: "lesson-spanish-greetings",
      status: "completed",
      score: 92,
      time_spent_seconds: 780,
      attempts: 1,
      started_at: isoDaysAgo(9),
      completed_at: isoDaysAgo(9),
      updated_date: isoDaysAgo(9),
      created_date: isoDaysAgo(9),
    },
    {
      id: "progress-2",
      user_id: "user-1",
      lesson_id: "lesson-french-cafe",
      status: "in_progress",
      score: 68,
      time_spent_seconds: 520,
      attempts: 2,
      started_at: isoDaysAgo(4),
      updated_date: isoDaysAgo(2),
      created_date: isoDaysAgo(4),
    },
    {
      id: "progress-3",
      user_id: "user-1",
      lesson_id: "lesson-japanese-intro",
      status: "in_progress",
      score: 74,
      time_spent_seconds: 430,
      attempts: 1,
      started_at: isoDaysAgo(2),
      updated_date: isoDaysAgo(1),
      created_date: isoDaysAgo(2),
    },
  ],
  flashcards: [
    {
      id: "flashcard-1",
      front: "hola",
      back: "hello",
      language: "Spanish",
      deck_name: "Spanish Basics",
      example_sentence: "Hola, como estas?",
      ease_factor: 2.5,
      interval_days: 1,
      repetitions: 2,
      next_review_date: isoDaysAgo(1),
      created_date: isoDaysAgo(14),
      updated_date: isoDaysAgo(5),
    },
    {
      id: "flashcard-2",
      front: "bonjour",
      back: "good day",
      language: "French",
      deck_name: "French Basics",
      example_sentence: "Bonjour, comment ca va?",
      ease_factor: 2.3,
      interval_days: 2,
      repetitions: 1,
      next_review_date: isoDaysAgo(2),
      created_date: isoDaysAgo(13),
      updated_date: isoDaysAgo(4),
    },
    {
      id: "flashcard-3",
      front: "arigato",
      back: "thank you",
      language: "Japanese",
      deck_name: "Japanese Basics",
      example_sentence: "Arigato gozaimasu.",
      ease_factor: 2.6,
      interval_days: 3,
      repetitions: 3,
      next_review_date: isoDaysAgo(1),
      created_date: isoDaysAgo(10),
      updated_date: isoDaysAgo(3),
    },
    {
      id: "flashcard-4",
      front: "geradeaus",
      back: "straight ahead",
      language: "German",
      deck_name: "Travel",
      example_sentence: "Gehen Sie geradeaus.",
      ease_factor: 2.4,
      interval_days: 4,
      repetitions: 2,
      next_review_date: isoDaysFromNow(2),
      created_date: isoDaysAgo(8),
      updated_date: isoDaysAgo(1),
    },
    {
      id: "flashcard-5",
      front: "merci",
      back: "thank you",
      language: "French",
      deck_name: "French Basics",
      example_sentence: "Merci beaucoup.",
      ease_factor: 2.7,
      interval_days: 5,
      repetitions: 4,
      next_review_date: isoDaysAgo(3),
      created_date: isoDaysAgo(7),
      updated_date: isoDaysAgo(2),
    },
  ],
  vocabularyEntries: [
    {
      id: "vocab-1",
      word: "aprender",
      language: "Spanish",
      definition: "to learn",
      translation: "learn",
      phonetic: "a-pren-DER",
      example_sentence: "Quiero aprender espanol este ano.",
      is_mastered: false,
      created_date: isoDaysAgo(7),
      updated_date: isoDaysAgo(2),
    },
    {
      id: "vocab-2",
      word: "boulangerie",
      language: "French",
      definition: "bakery",
      translation: "bakery",
      phonetic: "boo-lan-zhe-REE",
      example_sentence: "La boulangerie ouvre a sept heures.",
      is_mastered: true,
      created_date: isoDaysAgo(10),
      updated_date: isoDaysAgo(3),
    },
    {
      id: "vocab-3",
      word: "densha",
      language: "Japanese",
      definition: "train",
      translation: "train",
      phonetic: "DEN-sha",
      example_sentence: "Densha de gakkou ni ikimasu.",
      is_mastered: false,
      created_date: isoDaysAgo(5),
      updated_date: isoDaysAgo(1),
    },
  ],
  forumThreads: [
    {
      id: "thread-1",
      title: "How do you remember Spanish irregular verbs?",
      body: "I know the pattern once I see it, but I forget it a day later. What drills actually helped you?",
      language_tag: "Spanish",
      category: "grammar_help",
      upvotes: 24,
      view_count: 182,
      reply_count: 2,
      is_pinned: true,
      author_name: "Maria Silva",
      created_date: isoDaysAgo(6),
      updated_date: isoDaysAgo(1),
    },
    {
      id: "thread-2",
      title: "Best way to practice listening on short commutes",
      body: "I only have fifteen minutes each morning. Looking for routines that fit a short train ride.",
      language_tag: "French",
      category: "vocabulary",
      upvotes: 11,
      view_count: 87,
      reply_count: 1,
      is_pinned: false,
      author_name: "James Lee",
      created_date: isoDaysAgo(4),
      updated_date: isoDaysAgo(2),
    },
    {
      id: "thread-3",
      title: "Anyone interested in a weekly conversation exchange?",
      body: "I can help with English in exchange for beginner Japanese conversation practice.",
      language_tag: "Japanese",
      category: "find_partners",
      upvotes: 18,
      view_count: 95,
      reply_count: 0,
      is_pinned: false,
      author_name: "Alex Carter",
      created_date: isoDaysAgo(2),
      updated_date: isoDaysAgo(2),
    },
  ],
  forumReplies: [
    {
      id: "reply-1",
      thread_id: "thread-1",
      body: "I group them by pattern and then write one short sentence with each verb every day for a week.",
      upvotes: 9,
      is_accepted: true,
      author_name: "Yuki Tanaka",
      created_date: isoDaysAgo(5),
      updated_date: isoDaysAgo(5),
    },
    {
      id: "reply-2",
      thread_id: "thread-1",
      body: "Color coding helped me. I keep endings in one color and stem changes in another.",
      upvotes: 6,
      is_accepted: false,
      author_name: "Sofia Weber",
      created_date: isoDaysAgo(3),
      updated_date: isoDaysAgo(3),
    },
    {
      id: "reply-3",
      thread_id: "thread-2",
      body: "Shadow one short audio clip for the whole week instead of switching material every day.",
      upvotes: 4,
      is_accepted: false,
      author_name: "Maria Silva",
      created_date: isoDaysAgo(2),
      updated_date: isoDaysAgo(2),
    },
  ],
};
